version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://varshar9483:y98WRSKaJpcLJ7LK@cluster0.jhzly11.mongodb.net/cus_con
      - JWT_SECRET=abc123
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cconnect-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cconnect-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - cconnect-network

volumes:
  mongodb_data:

networks:
  cconnect-network:
    driver: bridge 